/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abel;


import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.JTextField;


/**
 *
 * @author Abel
 */
public class test extends javax.swing.JFrame {

    public login login;
    public Connection con;
    public ResultSet rset;
    public Statement stmt;

    public test() {
        initComponents();
        setLocationRelativeTo(null);
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/menghitungcc","root","");
            stmt = con.createStatement();
            JOptionPane.showMessageDialog(null,"Berhasil");
        } catch (Exception E) {
            JOptionPane.showMessageDialog(null,"Salah Prosedur");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        pilihan = new javax.swing.JLabel();
        pilihan1 = new javax.swing.JComboBox();
        pilihan2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfstroke = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfpiston = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        spek = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        tfhasil = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pilihan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pilihan.setText("PILIH KENDARAAN YANG ANDA ");

        pilihan1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "yamaha", "honda", "suzuki", "kawasaki", "pulsar" }));
        pilihan1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pilihan1ItemStateChanged(evt);
            }
        });
        pilihan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihan1ActionPerformed(evt);
            }
        });

        pilihan2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pilihan2ItemStateChanged(evt);
            }
        });
        pilihan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihan2ActionPerformed(evt);
            }
        });

        jButton1.setText("lanjut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("INGIN DI HITUNG");

        jLabel1.setText("Pilih Jenis Kendaraan :");

        jLabel2.setText("Masukkan Diameter Stroke :");

        jLabel4.setText("Masukkan Diameter Piston  :");

        jButton2.setText("hitung");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel5.setText("Hasilnya sebagai berikut        :");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abel/gmbr.png"))); // NOI18N

        spek.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spekAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(spek);

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel8.setText("koma(,) di ganti titik(.)");

        jMenu1.setText("Logout");

        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(pilihan1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pilihan2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(231, 231, 231)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfstroke, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(tfpiston))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(314, 314, 314))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pilihan)
                        .addGap(253, 253, 253))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pilihan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(tfstroke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfpiston, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pilihan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pilihan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jButton1)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(tfhasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihan2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pilihan2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihan2ItemStateChanged

    private void pilihan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihan2ActionPerformed
       

    }//GEN-LAST:event_pilihan2ActionPerformed

    private void pilihan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihan1ActionPerformed
               
        if (pilihan1.getSelectedItem().equals("...")){
        pilihan2.removeAllItems();
        }
        
        else if (pilihan1.getSelectedItem().equals("yamaha")){
        pilihan2.removeAllItems();
        pilihan2.addItem("mio");
        pilihan2.addItem("x-ride");
        pilihan2.addItem("vixion");
        pilihan2.addItem("scorpio");
        }
        
        else if (pilihan1.getSelectedItem().equals("honda")){
        pilihan2.removeAllItems();
        pilihan2.addItem("beat");
        pilihan2.addItem("vario");
        pilihan2.addItem("tiger");
        pilihan2.addItem("cbr");
        }
        
        else if (pilihan1.getSelectedItem().equals("suzuki")){
        pilihan2.removeAllItems();
        pilihan2.addItem("satria");
        pilihan2.addItem("nex");
        pilihan2.addItem("thunder");
        pilihan2.addItem("skywave");
        }
        
        else if (pilihan1.getSelectedItem().equals("kawasaki")){
        pilihan2.removeAllItems();
        pilihan2.addItem("ninja mono");
        pilihan2.addItem("ninja R");
        pilihan2.addItem("athlete");
        pilihan2.addItem("kaze R");
         }
        
    }//GEN-LAST:event_pilihan1ActionPerformed

    private void pilihan1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pilihan1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihan1ItemStateChanged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //logout
        try {
                login = new login();
                login.setVisible(true);
                this.dispose();
           
        } catch(Exception E) {
        
        
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void database() 
           throws SQLException{
            
    } 
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //yamaha
        if(pilihan1.getSelectedItem().equals("yamaha") && pilihan2.getSelectedItem().equals("mio")){
           String spek_m = null;
                try {
           String sql="Select * from spek where type_motor='mio' ";
           stmt =con.createStatement();
           rset = stmt.executeQuery(sql);
                while (rset.next())
              {
           spek_m = rset.getString("spek_motor");         
              }
           spek.setText(spek_m);
              } 
                catch (Exception E){
            JOptionPane.showMessageDialog(null, "Gagal Tampil Database");
        }  
        }
        else if (pilihan1.getSelectedItem().equals("yamaha") && pilihan2.getSelectedItem().equals("vixion")){
        String spek_m = null;
                try {
           String sql="Select * from spek where type_motor='vixion' ";
           stmt =con.createStatement();
           rset = stmt.executeQuery(sql);
                while (rset.next())
              {
           spek_m = rset.getString("spek_motor");         
              }
           spek.setText(spek_m);
              } 
                catch (Exception E){
            JOptionPane.showMessageDialog(null, "Gagal Tampil Database");
        }
        }
        else if (pilihan1.getSelectedItem().equals("yamaha") && pilihan2.getSelectedItem().equals("x-ride")){
        String spek_m = null;
                try {
           String sql="Select * from spek where type_motor='x-ride' ";
           stmt =con.createStatement();
           rset = stmt.executeQuery(sql);
                while (rset.next())
              {
           spek_m = rset.getString("spek_motor");         
              }
           spek.setText(spek_m);
              } 
                catch (Exception E){
            JOptionPane.showMessageDialog(null, "Gagal Tampil Database");
        }
        }
        else if (pilihan1.getSelectedItem().equals("yamaha") && pilihan2.getSelectedItem().equals("scorpio")){
        String spek_m = null;
                try {
           String sql="Select * from spek where type_motor='scorpio' ";
           stmt =con.createStatement();
           rset = stmt.executeQuery(sql);
                while (rset.next())
              {
           spek_m = rset.getString("spek_motor");         
              }
           spek.setText(spek_m);
              } 
                catch (Exception E){
            JOptionPane.showMessageDialog(null, "Gagal Tampil Database");
        }
        }
        
        //honda
        else if (pilihan1.getSelectedItem().equals("honda") && pilihan2.getSelectedItem().equals("beat")){
        String spek_m = null;
                try {
           String sql="Select * from spek where type_motor='beat' ";
           stmt =con.createStatement();
           rset = stmt.executeQuery(sql);
                while (rset.next())
              {
           spek_m = rset.getString("spek_motor");         
              }
           spek.setText(spek_m);
              } 
                catch (Exception E){
            JOptionPane.showMessageDialog(null, "Gagal Tampil Database");
        }
        }
        else if (pilihan1.getSelectedItem().equals("honda") && pilihan2.getSelectedItem().equals("cbr")){
        String spek_m = null;
                try {
           String sql="Select * from spek where type_motor='cbr' ";
           stmt =con.createStatement();
           rset = stmt.executeQuery(sql);
                while (rset.next())
              {
           spek_m = rset.getString("spek_motor");         
              }
           spek.setText(spek_m);
              } 
                catch (Exception E){
            JOptionPane.showMessageDialog(null, "Gagal Tampil Database");
        }
        }
        else if (pilihan1.getSelectedItem().equals("honda") && pilihan2.getSelectedItem().equals("tiger")){
        String spek_m = null;
                try {
           String sql="Select * from spek where type_motor='tiger' ";
           stmt =con.createStatement();
           rset = stmt.executeQuery(sql);
                while (rset.next())
              {
           spek_m = rset.getString("spek_motor");         
              }
           spek.setText(spek_m);
              } 
                catch (Exception E){
            JOptionPane.showMessageDialog(null, "Gagal Tampil Database");
        }
        }
        else if (pilihan1.getSelectedItem().equals("honda") && pilihan2.getSelectedItem().equals("vario")){
        String spek_m = null;
                try {
           String sql="Select * from spek where type_motor='vario' ";
           stmt =con.createStatement();
           rset = stmt.executeQuery(sql);
                while (rset.next())
              {
           spek_m = rset.getString("spek_motor");         
              }
           spek.setText(spek_m);
              } 
                catch (Exception E){
            JOptionPane.showMessageDialog(null, "Gagal Tampil Database");
        }
        }
        
        //suzuki
        else if (pilihan1.getSelectedItem().equals("suzuki") && pilihan2.getSelectedItem().equals("satria")){
        String spek_m = null;
                try {
           String sql="Select * from spek where type_motor='satria' ";
           stmt =con.createStatement();
           rset = stmt.executeQuery(sql);
                while (rset.next())
              {
           spek_m = rset.getString("spek_motor");         
              }
           spek.setText(spek_m);
              } 
                catch (Exception E){
            JOptionPane.showMessageDialog(null, "Gagal Tampil Database");
        }
        }
        else if (pilihan1.getSelectedItem().equals("suzuki") && pilihan2.getSelectedItem().equals("nex")){
        String spek_m = null;
                try {
           String sql="Select * from spek where type_motor='nex' ";
           stmt =con.createStatement();
           rset = stmt.executeQuery(sql);
                while (rset.next())
              {
           spek_m = rset.getString("spek_motor");         
              }
           spek.setText(spek_m);
              } 
                catch (Exception E){
            JOptionPane.showMessageDialog(null, "Gagal Tampil Database");
        }
        }
        else if (pilihan1.getSelectedItem().equals("suzuki") && pilihan2.getSelectedItem().equals("thunder")){
        String spek_m = null;
                try {
           String sql="Select * from spek where type_motor='thunder' ";
           stmt =con.createStatement();
           rset = stmt.executeQuery(sql);
                while (rset.next())
              {
           spek_m = rset.getString("spek_motor");         
              }
           spek.setText(spek_m);
              } 
                catch (Exception E){
            JOptionPane.showMessageDialog(null, "Gagal Tampil Database");
        }
        }
        else if (pilihan1.getSelectedItem().equals("suzuki") && pilihan2.getSelectedItem().equals("skywave")){
        String spek_m = null;
                try {
           String sql="Select * from spek where type_motor='skywave' ";
           stmt =con.createStatement();
           rset = stmt.executeQuery(sql);
                while (rset.next())
              {
           spek_m = rset.getString("spek_motor");         
              }
           spek.setText(spek_m);
              } 
                catch (Exception E){
            JOptionPane.showMessageDialog(null, "Gagal Tampil Database");
        }
        }
        
        //kawasaki
        else if (pilihan1.getSelectedItem().equals("kawasaki") && pilihan2.getSelectedItem().equals("ninja mono")){
        String spek_m = null;
                try {
           String sql="Select * from spek where type_motor='ninja mono' ";
           stmt =con.createStatement();
           rset = stmt.executeQuery(sql);
                while (rset.next())
              {
           spek_m = rset.getString("spek_motor");         
              }
           spek.setText(spek_m);
              } 
                catch (Exception E){
            JOptionPane.showMessageDialog(null, "Gagal Tampil Database");
        }
        }else if (pilihan1.getSelectedItem().equals("kawasaki") && pilihan2.getSelectedItem().equals("ninja R")){
        String spek_m = null;
                try {
           String sql="Select * from spek where type_motor='ninja R' ";
           stmt =con.createStatement();
           rset = stmt.executeQuery(sql);
                while (rset.next())
              {
           spek_m = rset.getString("spek_motor");         
              }
           spek.setText(spek_m);
              } 
                catch (Exception E){
            JOptionPane.showMessageDialog(null, "Gagal Tampil Database");
        }
        }else if (pilihan1.getSelectedItem().equals("kawasaki") && pilihan2.getSelectedItem().equals("kaze R")){
        String spek_m = null;
                try {
           String sql="Select * from spek where type_motor='kaze R' ";
           stmt =con.createStatement();
           rset = stmt.executeQuery(sql);
                while (rset.next())
              {
           spek_m = rset.getString("spek_motor");         
              }
           spek.setText(spek_m);
              } 
                catch (Exception E){
            JOptionPane.showMessageDialog(null, "Gagal Tampil Database");
        }
        }
        else if (pilihan1.getSelectedItem().equals("kawasaki") && pilihan2.getSelectedItem().equals("athlete")){
        String spek_m = null;
                try {
           String sql="Select * from spek where type_motor='athlete' ";
           stmt =con.createStatement();
           rset = stmt.executeQuery(sql);
                while (rset.next())
              {
           spek_m = rset.getString("spek_motor");         
              }
           spek.setText(spek_m);
              } 
                catch (Exception E){
            JOptionPane.showMessageDialog(null, "Gagal Tampil Database");
        }
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void spekAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spekAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_spekAncestorAdded

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            tfstroke.setText("");
            tfpiston.setText("");
            tfhasil.setText("");
            tfstroke.requestFocus();
            
                    
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
      // button hitung
      Float stroke = Float.valueOf(tfstroke.getText());
      Float piston = Float.valueOf(tfpiston.getText());
        
        
       //rumus menghitung cc nya gan
       Double hasil = (piston*piston)*stroke*3.14/4;
       
       String hasil2 = String.valueOf(hasil);
       String stroke2 = String.valueOf(stroke);
       String piston2 = String.valueOf (piston);
       
       //menampilkan nilai ke textfield
       tfhasil.setText(hasil2);
    }//GEN-LAST:event_jButton2ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel pilihan;
    private javax.swing.JComboBox pilihan1;
    private javax.swing.JComboBox pilihan2;
    private javax.swing.JTextPane spek;
    private javax.swing.JTextField tfhasil;
    private javax.swing.JTextField tfpiston;
    private javax.swing.JTextField tfstroke;
    // End of variables declaration//GEN-END:variables

    private JTextField setText(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
